### ISSUE TITLE
UI redirect flicker

### ISSUE THREAD

**Issue by ionescu-rares** [tim-js/timjs.ro-v2#15]
La load se face redirect catre "/home". Pe netlify uneori se poate sa flickere cu o pagina goala pe care scrie "Redirecting to...". Am incercat cateva fix-uri dar n-au mers decat local.

**Comment by andreipfeiffer** [comment]
@ionescu-rares asta nu e bug, din ce vad redirect-ul ala este explicit definit:
https://github.com/tim-js/timjs.ro-v2/blob/main/astro.config.mjs#L10

Eu as sugera sa stergem acel redirect, sa eliminam route-ul `/home`, si continutul ala sa se afiseze direct pe index, adica pe route-ul `/`.

**Comment by ionescu-rares** [comment]
Initial am folosit redirect in config fiindca netlify-ul pune trailing slash la finalul url-ului si astro local nu. Atunci devenea hacky implementarea pentru ruta de home ca sa handle-uie active tab-ul si pentru netlify si local.

Am gasit o setare faina de astro config `"trailingSlash: always"` si atunci nu mai e problema asta fiindca o sa fie consistente rutele 😃
