### ISSUE TITLE
Create events page

### ISSUE THREAD

**Issue by adrianfaciu** [tim-js/timjs.ro-v2#4]
This does not exist at all, so we need a new component.

https://github.com/tim-js/timjs.ro/wiki/Website-rewrite-2024#events

**Comment by andreipfeiffer** [comment]
Am pus niste continut pentru pagina de Events: https://github.com/tim-js/timjs.ro/wiki/Website-rewrite-2024#events

- din moment ce nu avem in plan ceva workshop-uri in viitorul apropiat, as sugera sa nu afisam pagina de **Workshops**, si sa ramana doar **Meetups** si **revo.js conference** (Workshops ar avea sens doar daca considerati ca ar fi util sa fie afisate evenimentele pe care le-am facut in trecut)
- momentan lipsesc ceva imagini, care cred ca ar trebui adaugate, eventual acel carusel ar merge pus (si) pe paginile astea 2
